@startuml
' Definições
actor Consumidor
rectangle "Api Gateway" as ApiGateway
rectangle "Serviço de Pedido" as PedidoServico
rectangle "Serviço de Produto" as ProdutoServico

' Relação
Consumidor --> ApiGateway : Adicionar produto ao carrinho
ApiGateway --> PedidoServico
PedidoServico --> ProdutoServico : Produto existe?
ProdutoServico --> PedidoServico
@enduml