@startuml
' Definições
actor Raiz
rectangle "Api Gateway" as ApiGateway
rectangle "Serviço de Inquilino" as InquilinoServico

' Relação
Raiz --> ApiGateway : Bloquear acesso do restaurante
ApiGateway --> InquilinoServico
@enduml