@startuml
' Definições
actor Consumidor
rectangle "Api Gateway" as ApiGateway
rectangle "Serviço de Conta" as ContaServico
rectangle "Serviço de Notificacao" as NotificacaoServico

' Relação
Consumidor --> ApiGateway : Cadastrar me
ApiGateway --> ContaServico
ContaServico --> NotificacaoServico : Solicita envio da mensagem
NotificacaoServico --> Consumidor : Envia mensagem
@enduml