@startuml
' Definições
actor Consumidor
rectangle "Api Gateway" as ApiGateway
rectangle "Serviço de Carrinho" as CarrinhoServico

' Relação
Consumidor --> ApiGateway : Listar produtos do carrinho
ApiGateway --> CarrinhoServico
@enduml
