@startuml
' Definições
actor Funcionario
rectangle "Api Gateway" as ApiGateway
rectangle "Serviço de Pedido" as PedidoServico

' Relação
Funcionario --> ApiGateway : Mudar estado do pedido
ApiGateway --> PedidoServico
@enduml