---
AWSTemplateFormatVersion: "2010-09-09"

Description: "This creates a Lambda function to send sms messages"

Parameters:
  StackBucketName:
    Type: String
    Default: ""

Resources:
  SMSNotificationFunction:
    Type: AWS::Lambda::Function
    DependsOn:
      - LambdaExecutionRole
    Properties:
      Code:
        S3Bucket: !Ref StackBucketName
        S3Key: "sms-notification-function.zip"        
      FunctionName: "wiyo-sms-notification"
      Handler: "index.handler"      
      Role: !Join
        - ""
        - - "arn:aws:iam::"
          - !Ref "AWS::AccountId"
          - ":role/wiyo-lambda-execution-role-for-sms-notification-function"
      Runtime: "nodejs18.x"
      Timeout: 6
  
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
                - sts:AssumeRole
            Principal: 
              Service: 
                - "lambda.amazonaws.com"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      RoleName:
        "wiyo-lambda-execution-role-for-sms-notification-function"
